name: CI CD

on:  
  push:
    branches: [ main ]

jobs:
  azure-deploy:    
    runs-on: ubuntu-latest   
    name: Deploy to azure
    steps:
    - name: Checkout code
      uses: actions/checkout@v2 
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.300 
        
    - name: Build
      run: dotnet build --configuration Release

    - name: Publish
      run: dotnet publish --configuration Release -o './myapp'

    - name: 'Deploy to Azure WebApp'
      uses: azure/webapps-deploy@v2
      with:
        app-name: webapp-0707
        slot-name: test
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE_TEST }}
        package: ./myapp